Move protos to sdk-core-protos
Nix sandboxes builds such that they cannot escape their manifest
directory. By moving the `protos` into `sdk-core-protos`, Nix will be
able to build crates that depend on `sdk-core-protos`.

Otherwise, the build script will fail:

    Error: Custom { kind: Other, error: "protoc failed: Could not make proto path relative: ../protos/local/temporal/sdk/core/core_interface.proto: No such file or directory\n" }